# Generated by Django 5.2.14 on 2026-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_project_resource_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(db_table='project_technologies', related_name='projects', to='portfolio.technology'),
        ),
        migrations.DeleteModel(
            name='ProjectTechnology',
        ),
    ]
